# Generated by Django 3.0.3 on 2020-02-21 03:58

import api.validators
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, validators=[api.validators.placa], verbose_name='Placa')),
                ('permanencia', models.CharField(default='0 minutos', max_length=21, verbose_name='Permanência')),
                ('entrada', models.DateTimeField(default=datetime.datetime(2020, 2, 21, 3, 58, 47, 288776, tzinfo=utc), verbose_name='Entrada')),
                ('pagamento', models.BooleanField(default=False, verbose_name='Pagamento')),
                ('saida', models.DateTimeField(default='2019-01-01T00:00:00.000000Z', verbose_name='Saída')),
                ('left', models.BooleanField(default=False, verbose_name='Left')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
            },
        ),
    ]
